export const MODULE_DEFINITIONS = [
  { code: 'A_DEPARTMENTS', name: 'Cơ cấu tổ chức', group: 'Hệ thống' },
  { code: 'A_USERS', name: 'Quản lý người dùng', group: 'Hệ thống' },
  { code: 'A_ROLES', name: 'Danh mục vai trò', group: 'Hệ thống' },
  { code: 'A_PERMISSIONS', name: 'Ma trận phân quyền', group: 'Hệ thống' },
  { code: 'A_DOCUMENTS', name: 'Hồ sơ giấy tờ & CO-CQ', group: 'Hệ thống' },
  { code: 'C_OVERVIEW', name: 'Tổng quan kho', group: 'Kho & Hàng hóa' },
  { code: 'C_WAREHOUSES', name: 'Quản lý kho vật lý', group: 'Kho & Hàng hóa' },
  { code: 'C_CATEGORIES', name: 'Danh mục hàng hóa', group: 'Kho & Hàng hóa' },
  { code: 'C_PRODUCT_TYPES', name: 'Loại hàng hóa', group: 'Kho & Hàng hóa' },
  { code: 'C_PRODUCTS', name: 'Quản lý sản phẩm SKU', group: 'Kho & Hàng hóa' },
  { code: 'C_SUPPLIERS', name: 'Danh sách Nhà cung cấp', group: 'Kho & Hàng hóa' },
  { code: 'C_REPORTS', name: 'Báo cáo tồn kho', group: 'Kho & Hàng hóa' },
  { code: 'B_CUSTOMERS', name: 'Quản lý Khách hàng', group: 'Kinh doanh' },
  { code: 'B_SALES_OVERVIEW', name: 'Doanh thu & sản lượng', group: 'Kinh doanh' },
  { code: 'B_QUOTATIONS', name: 'Quản lý Báo giá', group: 'Kinh doanh' },
  { code: 'B_ORDERS', name: 'Quản lý Đơn hàng', group: 'Kinh doanh' },
  { code: 'B_REPORTS', name: 'Báo cáo bán hàng & công nợ', group: 'Kinh doanh' },
  { code: 'B_SALES_PLANS', name: 'Kế hoạch kinh doanh', group: 'Kinh doanh' },
  { code: 'E_EXPENSES', name: 'Danh mục chi phí', group: 'Thu - Chi' },
  { code: 'E_PAYMENT_VOUCHERS', name: 'Lập phiếu chi & Duyệt', group: 'Thu - Chi' },
  { code: 'E_REVENUE_TYPES', name: 'Nhóm khoản thu', group: 'Thu - Chi' },
  { code: 'E_RECEIPT_VOUCHERS', name: 'Lập phiếu thu & Duyệt', group: 'Thu - Chi' },
  { code: 'E_CASHFLOW_REPORTS', name: 'Báo cáo dòng tiền', group: 'Thu - Chi' },
  { code: 'F_DASHBOARD_REVENUE', name: 'Dashboard Doanh thu', group: 'Dashboard' },
  { code: 'F_DASHBOARD_PROFIT', name: 'Dashboard Lợi nhuận', group: 'Dashboard' }
];
